services:

  server:
    build: ./server                  
    ports:
      - '8001:8001'                   
    environment:                     
      - DB_HOST=mysql                 
      - DB_USER=ali                   
      - DB_PASSWORD=root             
      - DB_NAME=crudmysql            
    depends_on:                       
      mysql:
        condition: service_healthy    
    restart: unless-stopped           

  # React frontend service
  client:
    build: ./client                   
    ports:
      - '3000:3000'                   
    depends_on:                       
      - server
    restart: unless-stopped          

  # MySQL service
  mysql:
    image: mysql:8.0                  
    environment:
      MYSQL_ROOT_PASSWORD: root    
      MYSQL_DATABASE: crudmysql        
      MYSQL_USER: ali                 
      MYSQL_PASSWORD: root             
    ports:
      - '3333:3306'                   
    volumes:
      - mysql-data:/var/lib/mysql      
      - ./initdb/init.sql:/docker-entrypoint-initdb.d/init.sql  
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]   
      interval: 10s
      timeout: 10s
      retries: 7                   
    restart: unless-stopped           

volumes:
  mysql-data:
