name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2  # Change to your region

      - name: Create EKS Cluster
        run: |
          set -e

          CLUSTER_NAME="my-project-cluster"
          NODE_GROUP_NAME="my-node-group"

          aws eks create-cluster \
            --name "$CLUSTER_NAME" \
            --kubernetes-version 1.21 \
            --role-arn arn:aws:iam::<your-account-id>:role/EKSClusterRole \
            --resources-vpc-config subnetIds=<subnet-1>,<subnet-2>,securityGroupIds=<sg-id>

          aws eks wait cluster-active --name "$CLUSTER_NAME"

          aws eks create-nodegroup \
            --cluster-name "$CLUSTER_NAME" \
            --nodegroup-name "$NODE_GROUP_NAME" \
            --node-role arn:aws:iam::<your-account-id>:role/EKSNodeRole \
            --subnets <subnet-1> <subnet-2> \
            --scaling-config minSize=1,maxSize=3,desiredSize=2

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name my-project-cluster --region us-west-2

      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      - name: Verify deployment
        run: |
          kubectl rollout status deployment/my-app-deployment
